# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Type

# Model Form Field configuration
form: $/iocare/bkpunewebservice/models/type/fields.yaml

# Model Class name
modelClass: Iocare\BkpuneWebservice\Models\Type

# Default redirect location
defaultRedirect: iocare/bkpunewebservice/type

# Create page
create:
    title: Create Type
    redirect: iocare/bkpunewebservice/type/update/:id
    redirectClose: iocare/bkpunewebservice/type

# Update page
update:
    title: Edit Type
    redirect: iocare/bkpunewebservice/type
    redirectClose: iocare/bkpunewebservice/type

# Preview page
preview:
    title: Preview Type